# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17H-QGMBEVV_AKesi8MoQlLwtYo3s-xvx
"""
import math
from math import sqrt

def sum(a,b):
    return a+b

def product(c,d):
    return c*d

